name: GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: luka-martins
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark

