name: GitHub Snake

on:
  schedule:
    # Gera o gráfico todo dia à meia-noite (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clona o código do repositório
      - uses: actions/checkout@v4

      # Usa o Snake para gerar os SVGs
      - uses: Platane/snk@v3
        with:
          github_user_name: luka-martins
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Adiciona e faz commit dos arquivos gerados
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Snake contribution graph"
          default_author: github_actions

